<?xml version="1.0" encoding="utf-8"?><Database Name="VietStock" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=dev.ueh.edu.vn;Initial Catalog=VietStock;Persist Security Info=True;User ID=sa" SettingsObjectName="processDataVietStock.Properties.Settings" SettingsPropertyName="VietStockConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.data" Member="datas">
    <Type Name="data">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="full_html" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ma_doanh_nghiep" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="pageSize" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pageNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.detail" Member="details">
    <Type Name="detail">
      <Column Name="uid" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="macp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="url" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="date" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="full_html" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>