#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace processDataVietStock
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VietStock")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdata(data instance);
    partial void Updatedata(data instance);
    partial void Deletedata(data instance);
    partial void Insertdetail(detail instance);
    partial void Updatedetail(detail instance);
    partial void Deletedetail(detail instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::processDataVietStock.Properties.Settings.Default.VietStockConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<data> datas
		{
			get
			{
				return this.GetTable<data>();
			}
		}
		
		public System.Data.Linq.Table<detail> details
		{
			get
			{
				return this.GetTable<detail>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.data")]
	public partial class data : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _full_html;
		
		private string _ma_doanh_nghiep;
		
		private System.Nullable<int> _pageSize;
		
		private System.Nullable<int> _pageNum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onfull_htmlChanging(string value);
    partial void Onfull_htmlChanged();
    partial void Onma_doanh_nghiepChanging(string value);
    partial void Onma_doanh_nghiepChanged();
    partial void OnpageSizeChanging(System.Nullable<int> value);
    partial void OnpageSizeChanged();
    partial void OnpageNumChanging(System.Nullable<int> value);
    partial void OnpageNumChanged();
    #endregion
		
		public data()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_html", DbType="NVarChar(MAX)")]
		public string full_html
		{
			get
			{
				return this._full_html;
			}
			set
			{
				if ((this._full_html != value))
				{
					this.Onfull_htmlChanging(value);
					this.SendPropertyChanging();
					this._full_html = value;
					this.SendPropertyChanged("full_html");
					this.Onfull_htmlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_doanh_nghiep", DbType="NVarChar(MAX)")]
		public string ma_doanh_nghiep
		{
			get
			{
				return this._ma_doanh_nghiep;
			}
			set
			{
				if ((this._ma_doanh_nghiep != value))
				{
					this.Onma_doanh_nghiepChanging(value);
					this.SendPropertyChanging();
					this._ma_doanh_nghiep = value;
					this.SendPropertyChanged("ma_doanh_nghiep");
					this.Onma_doanh_nghiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pageSize", DbType="Int")]
		public System.Nullable<int> pageSize
		{
			get
			{
				return this._pageSize;
			}
			set
			{
				if ((this._pageSize != value))
				{
					this.OnpageSizeChanging(value);
					this.SendPropertyChanging();
					this._pageSize = value;
					this.SendPropertyChanged("pageSize");
					this.OnpageSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pageNum", DbType="Int")]
		public System.Nullable<int> pageNum
		{
			get
			{
				return this._pageNum;
			}
			set
			{
				if ((this._pageNum != value))
				{
					this.OnpageNumChanging(value);
					this.SendPropertyChanging();
					this._pageNum = value;
					this.SendPropertyChanged("pageNum");
					this.OnpageNumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detail")]
	public partial class detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private string _macp;
		
		private string _url;
		
		private string _title;
		
		private string _date;
		
		private string _full_html;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void OnmacpChanging(string value);
    partial void OnmacpChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    partial void Onfull_htmlChanging(string value);
    partial void Onfull_htmlChanged();
    #endregion
		
		public detail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macp", DbType="NVarChar(50)")]
		public string macp
		{
			get
			{
				return this._macp;
			}
			set
			{
				if ((this._macp != value))
				{
					this.OnmacpChanging(value);
					this.SendPropertyChanging();
					this._macp = value;
					this.SendPropertyChanged("macp");
					this.OnmacpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="NVarChar(MAX)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(MAX)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(50)")]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_html", DbType="NVarChar(MAX)")]
		public string full_html
		{
			get
			{
				return this._full_html;
			}
			set
			{
				if ((this._full_html != value))
				{
					this.Onfull_htmlChanging(value);
					this.SendPropertyChanging();
					this._full_html = value;
					this.SendPropertyChanged("full_html");
					this.Onfull_htmlChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
